### ISSUE TITLE
Issue – Task 1 (Types).

### ISSUE THREAD

**Issue by javvaru** [subhanibabu/JavaScript#1]
@subhanibabu  please look at the comments which I shared for Task 1(Types) and implement it

getmiddlecharacter.js:
1. extra varible midLength 

vacation.js:
1. Discount  variable need to be declared before using it.
2. variable names should be in camel case.

**Comment by subhanibabu** [comment]
Extra variable used for different purpose in getmiddlecharacter.js.

implemented review comments for vacation.js:
