### ISSUE TITLE
Issue - Task2( scope)

### ISSUE THREAD

**Issue by javvaru** [subhanibabu/JavaScript#2]
@subhanibabu 

a-chain-adding-function.js: Good . Use proper names for function and variables

a-function-within-a-function.js: Good

function-composition.js: Good

calculating-with-functions.js : 
1.  you have duplicated line in every method from zero to nine. Keep that line in separate function and 
  call in every method.

**Comment by subhanibabu** [comment]
updated code as per review comments.
