### ISSUE TITLE
issue - this(task 3)

### ISSUE THREAD

**Issue by javvaru** [subhanibabu/JavaScript#3]
@subhanibabu 

Array Helpers.js
1. use predefined methods to calculate square and cube
2. you can use sum method inside average method,to remove duplicate code

Extract Nested Object Reference.js - Good

NewWithApply.js - Good

Usingclosurestoshareclassstate.js
1. You defined the property sum on Cat object. just maintain a sum variable, we don't need to call sum property explicitly. Instead you need to create weight property on every object we call using Cat constructor. This property need to be defined inside the cat constructor. Once a new object is created using new Cat('value', weight), it creates a property weight on that object. Then only you can set or get weight of that object.

2. Look into getter, settor methods of weight property. In the setter method you should keep track of sum and assign the new weight to local this._weight variable. Make sure the defined weight property name and local weight property name are different.

please ping me , if you have any questions.

**Comment by subhanibabu** [comment]
Implemented review comments.
